/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as ResetPasswordRouteImport } from './routes/reset-password';
import { Route as OauthCompleteRouteImport } from './routes/oauth-complete';
import { Route as LoginRouteImport } from './routes/login';
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ShareTokenRouteImport } from './routes/share/$token';
import { Route as EmbedTokenRouteImport } from './routes/embed/$token';

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any);
const OauthCompleteRoute = OauthCompleteRouteImport.update({
  id: '/oauth-complete',
  path: '/oauth-complete',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any);
const EmbedTokenRoute = EmbedTokenRouteImport.update({
  id: '/embed/$token',
  path: '/embed/$token',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/oauth-complete': typeof OauthCompleteRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/settings': typeof SettingsRoute;
  '/embed/$token': typeof EmbedTokenRoute;
  '/share/$token': typeof ShareTokenRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/oauth-complete': typeof OauthCompleteRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/settings': typeof SettingsRoute;
  '/embed/$token': typeof EmbedTokenRoute;
  '/share/$token': typeof ShareTokenRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/oauth-complete': typeof OauthCompleteRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/settings': typeof SettingsRoute;
  '/embed/$token': typeof EmbedTokenRoute;
  '/share/$token': typeof ShareTokenRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/oauth-complete'
    | '/reset-password'
    | '/settings'
    | '/embed/$token'
    | '/share/$token';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/oauth-complete'
    | '/reset-password'
    | '/settings'
    | '/embed/$token'
    | '/share/$token';
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/oauth-complete'
    | '/reset-password'
    | '/settings'
    | '/embed/$token'
    | '/share/$token';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  LoginRoute: typeof LoginRoute;
  OauthCompleteRoute: typeof OauthCompleteRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
  SettingsRoute: typeof SettingsRoute;
  EmbedTokenRoute: typeof EmbedTokenRoute;
  ShareTokenRoute: typeof ShareTokenRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/reset-password': {
      id: '/reset-password';
      path: '/reset-password';
      fullPath: '/reset-password';
      preLoaderRoute: typeof ResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/oauth-complete': {
      id: '/oauth-complete';
      path: '/oauth-complete';
      fullPath: '/oauth-complete';
      preLoaderRoute: typeof OauthCompleteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/forgot-password': {
      id: '/forgot-password';
      path: '/forgot-password';
      fullPath: '/forgot-password';
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/share/$token': {
      id: '/share/$token';
      path: '/share/$token';
      fullPath: '/share/$token';
      preLoaderRoute: typeof ShareTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/embed/$token': {
      id: '/embed/$token';
      path: '/embed/$token';
      fullPath: '/embed/$token';
      preLoaderRoute: typeof EmbedTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OauthCompleteRoute: OauthCompleteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  EmbedTokenRoute: EmbedTokenRoute,
  ShareTokenRoute: ShareTokenRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
