CREATE TABLE IF NOT EXISTS events (
  id          INT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id   BINARY(16)   NOT NULL,
  calendar_id INT UNSIGNED NOT NULL,
  title       VARCHAR(500) NOT NULL,
  all_day     TINYINT(1)   NOT NULL DEFAULT 0,
  start_at    DATETIME(3)  NOT NULL,
  end_at      DATETIME(3)  NOT NULL,
  timezone    VARCHAR(64)  NOT NULL DEFAULT 'UTC' COMMENT 'IANA timezone name (e.g. Asia/Tokyo)',
  color       VARCHAR(7)   NOT NULL DEFAULT '#42A5F5',
  location    VARCHAR(500) NOT NULL DEFAULT '',
  memo        TEXT         NOT NULL,
  url         VARCHAR(2000) NOT NULL DEFAULT '' COMMENT 'optional URL or meeting link',
  created_by  INT UNSIGNED NOT NULL,
  assigned_to         INT UNSIGNED NULL     COMMENT 'member responsible for this event',
  notification_offset INT          NULL     COMMENT 'minutes before event to notify; NULL = none',
  recurrence_rule JSON         NULL     COMMENT 'recurrence rule: {freq, interval, byDay, byMonthDay, bySetPos, until, count}',
  recurrence_end  DATETIME(3)  NULL     COMMENT 'effective end date for recurrence expansion queries',
  created_at  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_events_public_id (public_id),
  KEY idx_events_calendar_start (calendar_id, start_at),
  KEY idx_events_calendar_end (calendar_id, end_at),
  KEY idx_events_recurrence (calendar_id, recurrence_end),
  CONSTRAINT fk_events_calendar FOREIGN KEY (calendar_id) REFERENCES calendars (id) ON DELETE CASCADE,
  CONSTRAINT fk_events_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_events_assigned_to FOREIGN KEY (assigned_to) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
