// @ts-nocheck
import type { Calendar, CalendarEvent, Memo } from '@/types/calendar';
import { DateTime } from 'luxon';

const now = DateTime.now();
const thisMonth = now.startOf('month');

function dayAt(day: number, hour = 0, minute = 0): number {
  return thisMonth.set({ day, hour, minute }).toMillis();
}

export const MOCK_CALENDARS: Calendar[] = [
  {
    id: 'cal-work',
    name: '運営勤務',
    color: '#212121',
    members: [
      { id: 'm-sato', name: '佐藤', color: '#47B2F7', icon: '👩' },
      { id: 'm-yuki', name: 'ユウキ', color: '#F35F8C', icon: '👦' },
      { id: 'm-misaki', name: 'ミサキ', color: '#B38BDC', icon: '👧' },
      { id: 'm-takumi', name: 'タクミ', color: '#2ECC87', icon: '🧑' },
      { id: 'm-me', name: '自分', color: '#FDC02D', icon: '👤' },
    ],
    createdAt: Date.now() - 86400000 * 90,
  },
  {
    id: 'cal-personal',
    name: 'プライベート',
    color: '#47B2F7',
    members: [{ id: 'm-me', name: '自分', color: '#47B2F7', icon: '👤' }],
    createdAt: Date.now() - 86400000 * 60,
  },
  {
    id: 'cal-family',
    name: '家族',
    color: '#F35F8C',
    members: [
      { id: 'm-me', name: '自分', color: '#F35F8C', icon: '👤' },
      { id: 'm-partner', name: 'パートナー', color: '#B38BDC', icon: '👩' },
    ],
    createdAt: Date.now() - 86400000 * 30,
  },
];

export const MOCK_EVENTS: CalendarEvent[] = [
  // --- cal-work events ---
  {
    id: 'e1',
    calendarId: 'cal-work',
    title: '週次ミーティング',
    allDay: false,
    startAt: dayAt(2, 15, 0),
    endAt: dayAt(2, 16, 0),
    color: '#E73B3B',
    memberId: null,
    location: '会議室A',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e2',
    calendarId: 'cal-work',
    title: '佐藤 休み',
    allDay: true,
    startAt: dayAt(3, 0, 0),
    endAt: dayAt(3, 23, 59),
    color: '#47B2F7',
    memberId: 'm-sato',
    location: '',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e3',
    calendarId: 'cal-work',
    title: 'シフト',
    allDay: false,
    startAt: dayAt(4, 13, 0),
    endAt: dayAt(4, 22, 0),
    color: '#FDC02D',
    memberId: 'm-me',
    location: '',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e4',
    calendarId: 'cal-work',
    title: '外出',
    allDay: false,
    startAt: dayAt(5, 9, 0),
    endAt: dayAt(5, 18, 30),
    color: '#8F8F8F',
    memberId: null,
    location: '',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e5',
    calendarId: 'cal-work',
    title: 'チーム定例',
    allDay: false,
    startAt: dayAt(7, 15, 0),
    endAt: dayAt(7, 16, 0),
    color: '#E73B3B',
    memberId: null,
    location: 'オンライン',
    url: '',
    memo: '議題あり',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e6',
    calendarId: 'cal-work',
    title: 'リーダー会議',
    allDay: false,
    startAt: dayAt(7, 14, 0),
    endAt: dayAt(7, 15, 0),
    color: '#2ECC87',
    memberId: null,
    location: '',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e7',
    calendarId: 'cal-work',
    title: 'ユウキ 休み',
    allDay: true,
    startAt: dayAt(8, 0, 0),
    endAt: dayAt(8, 23, 59),
    color: '#F35F8C',
    memberId: 'm-yuki',
    location: '',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e8',
    calendarId: 'cal-work',
    title: '健康診断',
    allDay: true,
    startAt: dayAt(9, 0, 0),
    endAt: dayAt(9, 23, 59),
    color: '#B38BDC',
    memberId: null,
    location: '',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e9',
    calendarId: 'cal-work',
    title: 'シフト',
    allDay: false,
    startAt: dayAt(10, 12, 30),
    endAt: dayAt(10, 18, 30),
    color: '#FDC02D',
    memberId: 'm-me',
    location: '',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e10',
    calendarId: 'cal-work',
    title: 'タクミ シフト',
    allDay: false,
    startAt: dayAt(11, 0, 30),
    endAt: dayAt(11, 3, 0),
    color: '#2ECC87',
    memberId: 'm-takumi',
    location: '',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e11',
    calendarId: 'cal-work',
    title: 'チーム定例',
    allDay: false,
    startAt: dayAt(14, 15, 0),
    endAt: dayAt(14, 16, 0),
    color: '#E73B3B',
    memberId: null,
    location: 'オンライン',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e12',
    calendarId: 'cal-work',
    title: 'リーダー会議',
    allDay: false,
    startAt: dayAt(14, 14, 0),
    endAt: dayAt(14, 15, 0),
    color: '#2ECC87',
    memberId: null,
    location: '',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e13',
    calendarId: 'cal-work',
    title: '佐藤 休み',
    allDay: true,
    startAt: dayAt(15, 0, 0),
    endAt: dayAt(15, 23, 59),
    color: '#47B2F7',
    memberId: 'm-sato',
    location: '',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e14',
    calendarId: 'cal-work',
    title: 'ミサキ 休み',
    allDay: true,
    startAt: dayAt(16, 0, 0),
    endAt: dayAt(16, 23, 59),
    color: '#B38BDC',
    memberId: 'm-misaki',
    location: '',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e15',
    calendarId: 'cal-work',
    title: '外出',
    allDay: false,
    startAt: dayAt(17, 9, 0),
    endAt: dayAt(17, 18, 30),
    color: '#8F8F8F',
    memberId: null,
    location: '',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e16',
    calendarId: 'cal-work',
    title: 'シフト',
    allDay: false,
    startAt: dayAt(18, 13, 30),
    endAt: dayAt(18, 20, 0),
    color: '#FDC02D',
    memberId: 'm-me',
    location: '',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e17',
    calendarId: 'cal-work',
    title: 'チーム定例',
    allDay: false,
    startAt: dayAt(21, 15, 0),
    endAt: dayAt(21, 16, 0),
    color: '#E73B3B',
    memberId: null,
    location: 'オンライン',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e18',
    calendarId: 'cal-work',
    title: '外出',
    allDay: false,
    startAt: dayAt(22, 9, 0),
    endAt: dayAt(22, 18, 30),
    color: '#8F8F8F',
    memberId: null,
    location: '',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e19',
    calendarId: 'cal-work',
    title: 'ユウキ 休み',
    allDay: true,
    startAt: dayAt(23, 0, 0),
    endAt: dayAt(23, 23, 59),
    color: '#F35F8C',
    memberId: 'm-yuki',
    location: '',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e20',
    calendarId: 'cal-work',
    title: '面接',
    allDay: false,
    startAt: dayAt(24, 13, 0),
    endAt: dayAt(24, 17, 0),
    color: '#212121',
    memberId: null,
    location: 'オフィス',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'e21',
    calendarId: 'cal-work',
    title: 'チーム定例',
    allDay: false,
    startAt: dayAt(28, 15, 0),
    endAt: dayAt(28, 16, 0),
    color: '#E73B3B',
    memberId: null,
    location: 'オンライン',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // --- cal-personal events ---
  {
    id: 'ep1',
    calendarId: 'cal-personal',
    title: '通院',
    allDay: false,
    startAt: dayAt(6, 10, 0),
    endAt: dayAt(6, 11, 0),
    color: '#47B2F7',
    memberId: null,
    location: '駅前クリニック',
    url: '',
    memo: '定期検診',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'ep2',
    calendarId: 'cal-personal',
    title: 'ジム',
    allDay: false,
    startAt: dayAt(8, 7, 0),
    endAt: dayAt(8, 8, 30),
    color: '#26C6DA',
    memberId: null,
    location: 'スポーツジム',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'ep3',
    calendarId: 'cal-personal',
    title: '車検',
    allDay: true,
    startAt: dayAt(12, 0, 0),
    endAt: dayAt(12, 23, 59),
    color: '#F5A623',
    memberId: null,
    location: 'ディーラー',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'ep4',
    calendarId: 'cal-personal',
    title: 'ヘアカット',
    allDay: false,
    startAt: dayAt(19, 14, 0),
    endAt: dayAt(19, 16, 0),
    color: '#47B2F7',
    memberId: null,
    location: '',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // --- cal-family events ---
  {
    id: 'ef1',
    calendarId: 'cal-family',
    title: '買い物',
    allDay: false,
    startAt: dayAt(1, 11, 0),
    endAt: dayAt(1, 13, 0),
    color: '#F35F8C',
    memberId: null,
    location: 'ショッピングモール',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'ef2',
    calendarId: 'cal-family',
    title: '外食',
    allDay: false,
    startAt: dayAt(10, 18, 0),
    endAt: dayAt(10, 20, 0),
    color: '#F35F8C',
    memberId: null,
    location: 'レストラン',
    url: '',
    memo: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'ef3',
    calendarId: 'cal-family',
    title: '旅行',
    allDay: true,
    startAt: dayAt(25, 0, 0),
    endAt: dayAt(27, 23, 59),
    color: '#F35F8C',
    memberId: null,
    location: '',
    url: '',
    memo: '家族旅行',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

export const MOCK_MEMOS: Memo[] = [
  {
    id: 'memo1',
    calendarId: 'cal-work',
    title: 'シフト表作成',
    done: false,
    createdAt: Date.now(),
  },
  { id: 'memo2', calendarId: 'cal-work', title: '経費精算', done: true, createdAt: Date.now() },
  {
    id: 'memo3',
    calendarId: 'cal-personal',
    title: 'オイル交換',
    done: false,
    createdAt: Date.now(),
  },
];

/** Seed mock data into localStorage if empty. */
export function seedMockData() {
  const key = 'tt_calendars';
  const existing = localStorage.getItem(key);
  if (existing && existing !== '[]' && existing !== '[{"id":"default"') {
    return; // already has user data
  }

  localStorage.setItem('tt_calendars', JSON.stringify(MOCK_CALENDARS));
  localStorage.setItem('tt_events', JSON.stringify(MOCK_EVENTS));
  localStorage.setItem('tt_memos', JSON.stringify(MOCK_MEMOS));
  localStorage.setItem('tt_activeCalendarIds', JSON.stringify(MOCK_CALENDARS.map((c) => c.id)));

  // Force page reload to pick up new data
  window.location.reload();
}
